device: cuda:0
#fixed_size: [256, 192]
fixed_size: [224, 224]
num_joints: 17
epoch_num: 1
num_print: 50 # 每n个batch打印一次
start_epoch: 0
batch_size: 4
train_shuffle: True
drop_last: True
test_shuffle: False
momentum: 0.8
seed: 2023

path:
  data: ../data/coco2017/
  keypoints: ../trainer/person_keypoints.json
  output: ../weights/save_weights/
  pre_weight: ../weights/save_weights/model-5.pth
lr_scheduler:
  name: MultiStepLR
  lr_steps: [170, 200]
  lr_gamma: 0.1
  lr: 0.001
optimizer:
  name: AdamW
  learning_rate: 0.001
  weight_decay: 0.0001
scaler:
  name: StandardScaler




